apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-status-api-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Vegvizer-Ltd/DevOps-Assignment.git
    targetRevision: main
    path: helm/application
    helm:
      valueFiles:
        - ../../environments/dev/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
